- name: Install python devel env
  pacman: name={{ item }} state=present
  with_items:
    - base-devel
    - ipython
    - python-docs
    - python-virtualenv
    - python2
    - python2-docs
    - python2-pip
    - python2-virtualenv
  sudo: true

- name: Install python pip env
  pip: name={{ item }}
  with_items:
    - envdir
    - autoenv
  sudo: true
