---
#- name: Clone dotfiles for {{ user }}
#  sudo: yes
#  sudo_user: "{{ user }}"
#  git: repo=git://github.com/cdown/dotfiles.git dest=~{{ user }}/git/dotfiles accept_hostkey=yes
#
#- name: Set up dotfiles for {{ user }}
#  sudo: yes
#  sudo_user: "{{ user }}"
#  command: ./setup chdir="~{{ user }}/git/dotfiles"
#  changed_when: false
#
#- name: "Set {{ user }}'s dotfiles to push using ssh"
#  sudo: yes
#  sudo_user: "{{ user }}"
#  command: git remote set-url --push origin git@github.com:cdown/dotfiles.git chdir=~{{ user }}/git/dotfiles
#  changed_when: false

- name: Create homesick repos folder for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  shell: mkdir -p ~/.homesick/repos

- name: Clone homeshick for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  git: repo=https://github.com/andsens/homeshick.git dest=~/.homesick/repos/homeshick
